export const FETCH_INCIDENTS = 'FETCH_INCIDENTS';
export const CREATE_INCIDENT = 'CREATE_INCIDENT';
export const FETCH_INCIDENT = 'FETCH_INCIDENT';
export const UPDATE_INCIDENT = 'UPDATE_INCIDENT';
export const SET_LOADING = 'SET_LOADING';
